# Generated by Django 2.1.4 on 2018-12-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='手机号')),
                ('real_name', models.CharField(max_length=12, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('id_card_posi', models.CharField(max_length=256, verbose_name='身份证正面云链接')),
                ('id_card_nega', models.CharField(max_length=256, verbose_name='身份证反面云链接')),
                ('hand_card_posi', models.CharField(max_length=256, verbose_name='手持身份证云链接')),
                ('audit_pass', models.BooleanField(default=False, verbose_name='通过与否')),
            ],
            options={
                'verbose_name': '未审核用户表',
                'verbose_name_plural': '未审核用户表',
                'db_table': 'audittable',
            },
        ),
    ]
